export const chapters = [
  "1. The Living World",
  "2. Biological Classification",
  "3. Plant Kingdom",
  "4. Animal Kingdom",
  "5. Morphology of Flowering Plants",
  "6. Anatomy of Flowering Plants",
  "7. Structural Organisation in Animals",
  "8. Cell: The Unit of Life",
  "9. Biomolecules",
  "10. Cell Cycle and Cell Division",
  "11. Photosynthesis in Higher Plants",
  "12. Respiration in Plants",
  "13. Plant Growth and Development",
  "14. Breathing and Exchange of Gases",
  "15. Body Fluids and Circulation",
  "16. Excretory Products and their Elimination",
  "17. Locomotion and Movement",
  "18. Neural Control and Coordination",
  "19. Chemical Coordination and Integration",
  "20. Sexual Reproduction in Flowering Plants",
  "21. Human Reproduction",
  "22. Reproductive Health",
  "23. Principles of Inheritance and Variation",
  "24. Molecular Basis of Inheritance",
  "25. Evolution",
  "26. Human Health and Disease",
  "27. Microbes in Human Welfare",
  "28. Biotechnology: Principles and Processes",
  "29. Biotechnology and its Applications",
  "30. Organisms and Populations",
  "31. Ecosystem",
  "32. Biodiversity and Conservation"
];